<div class="container body">
    <div class="main_container">
        <div class="col-md-12">
            <div class="col-middle">
                <div class="text-center text-center">
                    <h1 class="error-number">404</h1>
                    <h2><?php echo $this->translate('Sorry but we couldn\'t find this page')?></h2>
                    <p><?php echo $this->translate('This page you are looking for does not exist')?> <a href="#"><?php echo $this->translate('Report this')?>?</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>