<div class="container body">
    <div class="main_container">
        <div class="col-md-12">
            <div class="col-middle">
                <div class="text-center">
                    <h1 class="error-number">500</h1>
                    <h2><?php echo $this->translate('Internal Server Error')?></h2>
                    <p><?php echo $this->translate('We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.')?> <a href="#"><?php echo $this->translate('Report this')?>?</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>