<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu">
            <li class="header"><?php echo $this->translate('Main Navigation') ?></li>
            <li>
                <a href="#">
                    <i class="fa fa-calendar"></i>
                    <span><?php echo $this->translate('Active products') ?></span>
                </a>
            </li>
        </ul>
    </section>
</aside>