<?php

//todo need use strategy for view

use Core\Service\LocaleService;
use Zend\ServiceManager\ServiceLocatorInterface;

/** @var ServiceLocatorInterface $serviceManager */
$serviceManager = $this->getHelperPluginManager()->getServiceLocator();
/** @var LocaleService  $localeService */
$localeService = $serviceManager->get(LocaleService::class);
?>

<header class="main-header">
    <nav class="navbar navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <a href="/" class="navbar-brand"><b>YouFold</b></a>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                    <i class="fa fa-bars"></i>
                </button>
            </div>

            <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Main') ?> </a></li>
                </ul>
            </div>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class=""><a href="<?php echo $this->url('user-index', ['action' => 'sign-in']) ?>"><?php echo $this->translate('Sign In') ?> </a></li>
                    <li class=""><a href="<?php echo $this->url('user-index', ['action' => 'sign-up']) ?>"><?php echo $this->translate('Sign Up') ?> </a></li>

                    <li>
                        <select id="locale" data-url="<?php echo $this->url('core-index', ['action' => 'locale']) ?>">
                            <?php foreach ($localeService->getLocaleList() as $key=>$locale) : ?>
                                <option <?php if ($localeService->isCurrentLocale($locale)) echo 'selected' ?>
                                        value="<?php echo $key ?>"><?php echo ucfirst($key) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </li>

                </ul>
            </div>

        </div>
    </nav>
</header>