<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <?php
    echo $this->headTitle('YouFold')->setSeparator(' - ')->setAutoEscape(false);

    echo $this->cpanelStylesheet();
    echo $this->application();

    echo $this->headStyle();
    echo $this->headLink();

    echo $this->jquery();

    echo $this->headScript();
    ?>

    <style>

    </style>
</head>
<body class="hold-transition login-page">

<?php
echo $this->partial('layout/modal/_flash-messenger-modal');
?>


<div class="login-box">
    <div class="login-logo">
        <a href="/"><b>YouFold</b></a>
    </div>

    <div class="login-box-body">
        <?php echo $this->content; ?>

    </div>
</div>

<?php echo $this->cpanelJs()?>
</body>
</html>
