<?php
/**
 * @var \User\Form\SignInForm $signInForm
 */
$this->headTitle($this->translate('Sign in'));

$signInForm->prepare();
?>

<p class="login-box-msg"><?php echo $this->translate('Sign in to start your session') ?></p>

<?php echo $this->form()->openTag($signInForm); ?>
<div class="form-group has-feedback">

    <?php echo $this->formElement($signInForm->get('email')) ?>
    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>

    <span class="help-block bb-error">
        <?php echo $this->formElementErrors($signInForm->get('email'))?>
    </span>
</div>
<div class="form-group has-feedback">
    <?php echo $this->formElement($signInForm->get('password')) ?>
    <span class="glyphicon glyphicon-lock form-control-feedback"></span>

    <span class="help-block bb-error">
        <?php echo $this->formElementErrors($signInForm->get('password'))?>
    </span>
</div>
<div class="row">

    <div class="col-xs-12">
        <?php echo $this->formElement($signInForm->get('csrf')) ?>
        <?php echo $this->formElement($signInForm->get('submit'))?>

        <span class="help-block bb-error">
            <?php echo $this->formElementErrors($signInForm->get('csrf')) ?>
        </span>
    </div>

</div>
<?php echo $this->form()->closeTag(); ?>

<a href="/" class="text-center"><?php echo $this->translate('Register a new membership')?></a>
<br>
<a href="/" class="text-center"><?php echo $this->translate('Back to Home')?></a>
