<?php
    $this->headScript()->captureStart();
        echo $this->partial('script/index.js');
    $this->headScript()->captureEnd();
?>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h1><?php echo $this->translate('Hello world!')?></h1>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <h2>
                    <?php echo $this->translate('Core module')?>
                </h2>
            </div>
        </div>
    </div>
</div>